server:
  port: 8080

spring:
  datasource:
    # 显式指定使用 Druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接串
    url: jdbc:mysql://localhost:3306/caizhitong?connectTimeout=30000&remarks=true&useInformationSchema=true&tinyInt1isBit=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: root

    # Druid 连接池参数
    druid:
      keep-alive: true
      keep-alive-between-time-millis: 60000
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-pool-prepared-statement-per-connection-size: 20
# =========================================================
# 2. MyBatis-Plus 配置
# =========================================================
mybatis-plus:
  # 指定 XML 文件的位置
  mapper-locations: classpath*:/mapper/**/*.xml

  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

  # 开启 SQL 日志打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# =========================================================
# 3. Sa-Token 权限配置 (内存模式)
# =========================================================
sa-token:
  timeout: 43200
  token-name: satoken
  active-timeout: 1800
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: true